### ISSUE TITLE
Cannot install from git but can install with pip install -e . 

### ISSUE THREAD

**Issue by bastienboutonnet** [bastienboutonnet/sheetload#27]
If I clone and do `pip install -e .` from the sheetload folder then call `sheetload --version` all seems good.

If I install from git 
```pip install git+ssh://git@github.com/bastienboutonnet/sheetload.git@v1.0.0rc4```

I run into this error:
```
Traceback (most recent call last):
  File "/Users/bboutonnet@tripactions.com/venvs/sheetload_test_install/bin/sheetload", line 11, in <module>
    load_entry_point('sheetload==1.0.0rc3', 'console_scripts', 'sheetload')()
  File "/Users/bboutonnet@tripactions.com/venvs/sheetload_test_install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/bboutonnet@tripactions.com/venvs/sheetload_test_install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/Users/bboutonnet@tripactions.com/venvs/sheetload_test_install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/Users/bboutonnet@tripactions.com/venvs/sheetload_test_install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'sheetload'
```

No goddamn idea what the issue is...

**Comment by optroodt** [comment]
Maybe add `py_modules=['sheetload']` to your `setup.py`?
